"""Regenerate a sanitized source snapshot from an explicitly reviewed file list.

Never publishes, executes private code, reads key stores, or imports Git history.
New source paths require deliberate review and an edit to export-inputs.json.
"""
import argparse
import json
from pathlib import Path
import re
import shutil
import tempfile

ROOT = Path(__file__).resolve().parents[1]
DESTINATION = ROOT / 'security-infrastructure'
DIGEST = re.compile(r'(?<![A-Za-z0-9])[0-9a-fA-F]{32,}(?![A-Za-z0-9])')
EMAIL = re.compile(r'[A-Za-z0-9_.+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}')
WINDOWS_PATH = re.compile(r'[A-Za-z]:\\[^"\r\n]*')
SECRET_PATTERNS = [
    re.compile(r'-----BEGIN (?:[A-Z ]+ )?(?:PRIVATE KEY|PUBLIC KEY|CERTIFICATE)-----'),
    re.compile(r'gh[pousr]_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{20,}'),
    re.compile(r'AKIA[0-9A-Z]{16}|sk-[A-Za-z0-9_-]{20,}'),
    re.compile(r'(?i)(?:password|api_key|access_token|client_secret)\s*[:=]\s*["\x27][^"\x27\s]{8,}["\x27]'),
    re.compile(r'["\x27][A-Za-z0-9+/]{80,}={0,2}["\x27]'),
]


def validate_text(name, text):
    if '\0' in text or any(p.search(text) for p in SECRET_PATTERNS):
        raise ValueError('Potential key, credential, encoded blob or binary in ' + name)
    if DIGEST.search(text):
        raise ValueError('Recorded digest in ' + name)


def sanitize(name, text):
    # Placeholders deliberately cannot satisfy a cryptographic integrity check.
    # No replacement digest is computed from an untrusted candidate contract.
    text, digests = DIGEST.subn('PUBLIC_DIGEST_REMOVED', text)
    text, emails = EMAIL.subn('PUBLIC_IDENTITY_REMOVED', text)
    text, paths = WINDOWS_PATH.subn('PUBLIC_DEPLOYMENT_PATH_REMOVED', text)
    text, identifiers = re.subn(
        r'(?m)^(known_existing_nv_handles|key_name|observed_[A-Za-z0-9_]+)=.*$',
        r'\1=PUBLIC_DEPLOYMENT_VALUE_REMOVED', text)
    validate_text(name, text)
    return text, {'digests':digests,'identities':emails,'paths':paths,'deployment_values':identifiers}


def prepare(source):
    entries = json.loads((ROOT / 'tools/export-inputs.json').read_text())['files']
    if len(set(entries)) != len(entries):
        raise ValueError('Duplicate input paths')
    current = {p.relative_to(source).as_posix() for p in (source / 'src').rglob('*')
               if p.is_file() and p.suffix in {'.cs', '.csproj'}
               and not {'bin','obj'}.intersection(p.relative_to(source).parts)}
    reviewed = {p for p in entries if p.startswith('src/')}
    if current != reviewed:
        raise ValueError('Review added/removed source paths in export-inputs.json: ' + str(sorted(current ^ reviewed)))
    outputs = {}
    records = []
    for name in entries:
        relative = Path(name)
        if relative.is_absolute() or '..' in relative.parts:
            raise ValueError('Unsafe input path')
        path = source / relative
        if not path.resolve().is_relative_to(source) or any(p.is_symlink() for p in [path,*path.parents]):
            raise ValueError('Symlink or source escape: ' + name)
        text, changes = sanitize(name, path.read_text(encoding='utf-8-sig'))
        # Templates are documentation, never runtime trust anchors.
        target = 'specification-templates/' + name + '.example' if name.endswith('.conf') else name
        outputs[target] = text
        records.append({'source': name, 'published': target, 'redactions': changes})
    outputs['export-manifest.json'] = json.dumps({'format':1, 'files':records},indent=2)+'\n'
    return outputs


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', required=True, type=Path, help='Private TrustBroker project root')
    parser.add_argument('--check', action='store_true', help='Compare regenerated bytes without writing')
    args = parser.parse_args()
    source = args.source.resolve()
    if source == DESTINATION or source.is_relative_to(DESTINATION):
        raise ValueError('Source must be the private project, not the public snapshot')
    if DESTINATION.is_symlink() or any(p.is_symlink() for p in DESTINATION.parents):
        raise ValueError('Symlink in destination ancestry')
    outputs = prepare(source)
    utilities = {}
    for entry in json.loads((ROOT / 'docs/source-manifest.json').read_text())['components']:
        target = Path(entry['path'])
        if target.is_absolute() or '..' in target.parts or target.parts[:2] != ('src', 'I-Mortal.Security'):
            raise ValueError('Unsafe utility target')
        if any(p.is_symlink() for p in [ROOT / target, *(ROOT / target).parents]):
            raise ValueError('Symlink in utility target')
        upstream = Path(entry['upstream']).relative_to('security-infrastructure').as_posix()
        utilities[target] = outputs[upstream]
    if args.check:
        actual = {p.relative_to(DESTINATION).as_posix() for p in DESTINATION.rglob('*')
                  if p.is_file() and not {'bin','obj'}.intersection(p.relative_to(DESTINATION).parts)}
        if actual != set(outputs) or any((DESTINATION/p).read_bytes() != t.encode('utf-8') for p,t in outputs.items()):
            raise ValueError('Export differs; regenerate and review before publishing')
        if any((ROOT / p).read_bytes() != t.encode('utf-8') for p,t in utilities.items()):
            raise ValueError('Public utility copies differ from the export')
    else:
        # Validate every input before changing the generated tree. Only paths in
        # the previous generated manifest may be removed during synchronization.
        previous = DESTINATION / 'export-manifest.json'
        old = json.loads(previous.read_text())['files'] if previous.exists() else []
        for entry in old:
            rel = Path(entry['published'])
            if rel.is_absolute() or '..' in rel.parts:
                raise ValueError('Unsafe previous manifest')
        for path in DESTINATION.rglob('*'):
            if path.is_symlink():
                raise ValueError('Symlink in destination')
        with tempfile.TemporaryDirectory(prefix='imortal-export-') as tmp:
            stage = Path(tmp)
            for name,text in outputs.items():
                target = stage / name
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(text, encoding='utf-8', newline='\n')
            for entry in old:
                if entry['published'] not in outputs:
                    (DESTINATION / entry['published']).unlink(missing_ok=True)
            for name in outputs:
                target = DESTINATION / name
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(stage / name,target)
            for name,text in utilities.items():
                (ROOT / name).write_text(text, encoding='utf-8', newline='\n')
    print('SANITIZED_EXPORT=PASS; FILES=' + str(len(outputs)))


if __name__ == '__main__':
    main()
